### ISSUE TITLE
Working in a subsite

### ISSUE THREAD

**Issue by felixSchl** [geraldus/yesod-form-richtext#2]
Hey, how would you use `snHtmlField` in a yesod subsite?

```haskell
        • Couldn't match type ‘IO’ with ‘HandlerT master IO’
          Expected type: AForm (Handler master) EditForm
            Actual type: AForm (HandlerT MyYesodSubsite IO) EditForm
```

As far as I can tell, there's no `liftHandlerT` equivalent over fields, so not sure as to how to achieve this.

**Comment by geraldus** [comment]
Version `0.1.0.1` is on __Hackage__ now!

**Comment by skinner33** [comment]
Could you please revert the merge of #3 and re-release as 0.1.0.2?
This is an API change and according to semver this would be a major version bump and not a patch level.

As stackage follows this guideline, and this package is included in stackage, the new release was included in lts-8.20 and effectively broke a few applications for me ..

**Comment by geraldus** [comment]
@skinner33 sorry for that.  I don't have any working project with subsites right now.  I asked previous PR author to check if Monad constraint will satisfy subsites too.  Will fix stuff soon.  Again, apologize any inconveniences.

**Comment by felixSchl** [comment]
I just checked it, @skinner33 is correct and #4 does work

**Comment by geraldus** [comment]
@felixSchl thanks!
